services:
  api:
    image: ovu_image
    container_name: ovu_api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 7000:7000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
        - redis
    networks:
      - docker_network

  redis:
    image: redis
    container_name: ovu_redis
    ports:
      - 6379:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - docker_network
    
  # celery:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.celery
  #   restart: always
  #   image: celery_image
  #   container_name: celery_container
  #   depends_on:
  #     - redis
  #   networks:
  #     - docker_network
  #   env_file:
  #     - .env

networks:
  docker_network:
    driver: bridge
