services:
  api:
    image: ovu_image
    container_name: ovu_api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 7000:7000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
        - redis
    networks:
      - ovu_network

  redis:
    image: redis
    container_name: ovu_redis
    ports:
      - 6380:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - ovu_network

#  metasploit:
#    image: metasploitframework/metasploit-framework:latest
#    container_name: metasploit-scanner
#    ports:
#      - "55553:55553"
#      - "4444:4444"
#    env_file:
#      - .env
#    volumes:
#      - metasploit_data:/home/msf/.msf4
#      - /tmp/msf:/tmp/data
#    restart: unless-stopped
#    command:
#      - "/usr/src/metasploit-framework/msfrpcd"
#      - "-P"
#      - "password"
#      - "-S"
#      - "-f"
#      - "-a"
#      - "0.0.0.0"
#      - "-p"
#      - "55553"
#    networks:
#      - ovu_network

networks:
  ovu_network:
    driver: bridge

volumes:
  metasploit_data:
