"""new col

Revision ID: 5d3d3de57c1e
Revises: 
Create Date: 2025-10-09 14:52:19.288642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3d3de57c1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_results', sa.Column('discovered_endpoints', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('tenant_name', sa.String(length=50), nullable=True))
    op.drop_column('users', 'verify_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'tenant_name')
    op.drop_column('scan_results', 'discovered_endpoints')
    # ### end Alembic commands ###
