"""addedNewCol

Revision ID: 6007cc23538e
Revises: 676e9a43c54d
Create Date: 2025-10-29 14:24:41.012571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6007cc23538e'
down_revision: Union[str, None] = '676e9a43c54d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_size', sa.String(length=70), nullable=True))
    op.add_column('users', sa.Column('industry', sa.String(length=70), nullable=True))
    op.add_column('users', sa.Column('registration_type', sa.String(length=70), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=170),
               existing_nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'company',
               existing_type=sa.VARCHAR(length=70),
               type_=sa.String(length=170),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company',
               existing_type=sa.String(length=170),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=170),
               type_=sa.VARCHAR(length=70),
               existing_nullable=True)
    op.drop_column('users', 'registration_type')
    op.drop_column('users', 'industry')
    op.drop_column('users', 'company_size')
    # ### end Alembic commands ###
