"""newCol

Revision ID: dec2b8cb8494
Revises: 5cc34064bc83
Create Date: 2025-10-10 11:17:32.262940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec2b8cb8494'
down_revision: Union[str, None] = '5cc34064bc83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=70), nullable=True))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=70),
               existing_nullable=True)
    op.alter_column('users', 'company',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=70),
               existing_nullable=True)
    op.alter_column('webhook_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'company',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
